name: cdcapron
favicon: null
layout_spectrum: 0.8049928310792893
typography_spectrum: 0.725014939205721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2609728865791112
  lightness: 0.9265006119385362
  saturation: 0.9782630631234497
  rhythmicContrast: 0.9343272368423641
purpose: []
